[package]
name = "relm4"
authors = ["Aaron Erhardt <aaron.erhardt@t-online.de>"]
edition = "2021"
version = "0.4.5"
description = "An idiomatic GUI library inspired by Elm and based on gtk4-rs"
repository = "https://github.com/Relm4/relm4"
readme = "README.md"
license = "Apache-2.0 OR MIT"
documentation = "https://docs.rs/relm4/"

keywords = ["gui", "gtk", "gtk4"]
categories = ["gui"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[workspace]
members = [
    "relm4-components",
    "relm4-examples",
    "relm4-examples/libadwaita",
    "relm4-macros",
]

[package.metadata.docs.rs]
all-features = true
cargo-args = ["-Zunstable-options", "-Zrustdoc-scrape-examples=examples"]

[dependencies]
adw = { version = "0.1", optional = true, package = "libadwaita" }
panel = { version = "0.1.0-alpha-0", optional = true, package = "libpanel" }
async-trait = { version = "0.1", optional = true }
fragile = "1.1"
futures-core = "0.3"
gtk = { version = "0.4.6", package = "gtk4" }
log = "0.4.14"
once_cell = "1.8"

#relm4-macros = { version = "0.4.3", optional = true }
relm4-macros = { path = "relm4-macros", optional = true }

tokio = { version = "1.15", optional = true, features = ["rt"] }

[features]
default = []
# The dox feature can be used for building the docs without the dependencies and requires Rust Nightly
dox = ["gtk/dox", "adw/dox", "panel/dox"]
libadwaita = ["adw"]
libpanel = ["panel"]
tokio-rt = ["tokio", "async-trait"]
macros = ["relm4-macros"]
all = [
    "tokio-rt",
    "libadwaita",
    "macros",
] # dox is not part of the 'all' feature, because it is only used for generating the documentation


[dev-dependencies]
futures-channel = "0.3"
futures-executor = "0.3"
# Macros required to run tests.
relm4-macros = { path = "relm4-macros" }
