[package]
name = "relm4"
documentation = "https://docs.rs/relm4/"

version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
readme.workspace = true
license.workspace = true
description.workspace = true

homepage.workspace = true
repository.workspace = true

keywords.workspace = true
categories.workspace = true

[package.metadata.docs.rs]
all-features = true
cargo-args = ["-Zunstable-options", "-Zrustdoc-scrape-examples"]

[features]
default = ["macros"]
# The dox feature can be used for building the docs without the dependencies and requires Rust Nightly
dox = ["gtk/dox", "adw/dox", "panel/dox"]
libadwaita = ["adw"]
libpanel = ["panel"]
macros = ["relm4-macros"]

gnome_43 = ["gtk/gnome_43", "adw/v1_2"]
gnome_42 = ["gtk/gnome_42"]

# All features except docs. This is also used in the CI
all = ["macros", "libadwaita", "panel"]

[dependencies]
adw = { version = "0.2", optional = true, package = "libadwaita" }

flume = "0.10.14"
futures = "0.3.26"
fragile = "2.0.0"
gtk = { version = "0.5", package = "gtk4" }
once_cell = "1.17"
panel = { version = "0.1", optional = true, package = "libpanel" }
tokio = { version = "1.25", features = ["rt", "rt-multi-thread", "sync"] }

relm4-macros = { version = "0.5.1", path = "../relm4-macros", optional = true }
tracing = "0.1.37"
async-trait = "0.1.64"

[dev-dependencies]
relm4-macros = { path = "../relm4-macros" }

# For the benchmarks
criterion = { version = "0.4", default-features = false }

# For the examples
tokio = { version = "1.25", features = [
    "rt",
    "macros",
    "time",
    "rt-multi-thread",
] }
futures = "0.3.26"
rand = "0.8.5"
tracker = "0.2"
reqwest = "0.11.14"
tracing-subscriber = "0.3.16"

[[bench]]
name = "stress_test"
harness = false

# Make sure that the examples are scraped
[[example]]
name = "simple"
path = "examples/simple.rs"
doc-scrape-examples = true
