[package]
name = "relm4-macros"
authors = ["Aaron Erhardt <aaron.erhardt@t-online.de>"]
edition = "2021"
version = "0.4.0-beta.1"
description = "An idiomatic GUI library inspired by Elm and based on gtk4-rs"
repository = "https://github.com/AaronErhardt/relm4"
readme = "README.md"
license = "Apache-2.0 OR MIT"
documentation = "https://aaronerhardt.github.io/docs/relm4/relm4_macros/"

keywords = ["gui", "gtk", "gtk4"]
categories = ["gui"]

[lib]
proc-macro = true
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "1.0", features = ["full", "extra-traits"] }

[dev-dependencies]
gtk = { version = "0.3", package = "gtk4" }
relm4 = { path = ".." }
