[package]
name = "relm4-components"
readme = "README.md"
documentation = "https://docs.rs/relm4_components/"

version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description.workspace = true

homepage.workspace = true
repository.workspace = true

keywords.workspace = true
categories.workspace = true

[package.metadata.docs.rs]
features = ["dox"]
cargo-args = ["-Zunstable-options", "-Zrustdoc-scrape-examples"]

[dependencies]
once_cell = "1.17"
relm4 = { version = "0.5.1", path = "../relm4", features = ["macros"] }
reqwest = { version = "0.11.14", optional = true }
tracker = "0.2.0"

[features]
default = []
dox = ["relm4/dox", "web"]
web = ["reqwest"]

[[example]]
name = "web_image"
required-features = ["web"]