name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-20.04
#    runs-on: ubuntu-
    container:
      image: ghcr.io/gtk-rs/gtk4-rs/gtk4:latest
#      image: ubuntu:21.04
    strategy:
      matrix:
        rust:
          - stable
          - beta
          - nightly
          - "1.56.0"
    env:
        DISPLAY: ":99.0"
        # Workaround to avoid getting stuck by apt about choosing a timezone.
        DEBIAN_FRONTEND: noninteractive
        TZ: America/New_York
    steps:
#      - run: apt update -y
#      - run: apt upgrade -y
#      - run: apt install -y libgtk-4-dev curl
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          override: true

      - name: "clippy"
        run: cargo clippy -- --deny warnings

      # nightly
      - name: "relm: build nightly"
        run: cargo build
        if: matrix.rust == 'nightly'
      # not nightly
      - name: "relm: build"
        run: cargo build
        if: matrix.rust != 'nightly'

      - name: "relm: check examples"
        run: cargo check --manifest-path relm4-examples/Cargo.toml --examples

      - uses: bcomnes/cleanup-xvfb@v1.0.6
