name: CI

on:
  push:
    branches: [ main, stable ]
  pull_request:
    branches: [ main, stable ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/relm4/relm4/docs:latest
    strategy:
      matrix:
        rust:
          - stable
          - beta
          - nightly
          - "1.61"
    env:
        DISPLAY: ":99.0"
    steps:
      - uses: actions/checkout@v2
      - uses: rui314/setup-mold@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          override: true

      - name: "clippy"
        run: cargo clippy -- --deny warnings

      - name: "clippy all features"
        run: cargo clippy --all-features -- --deny warnings

      # nightly
      - name: "test nightly"
        run: xvfb-run --auto-servernum cargo test
        if: matrix.rust == 'nightly'
      # not nightly
      - name: "test"
        run: xvfb-run --auto-servernum cargo test
        if: matrix.rust != 'nightly'

      - name: "check examples"
        run: cargo clippy --examples -- --deny warnings

      - uses: bcomnes/cleanup-xvfb@v1.0.6

  fmt:
    name: rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: rustup component add rustfmt
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

  codespell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: codespell-project/actions-codespell@master
        with:
          check_filenames: true
          ignore_words_list: crate,statics